name: Atualizar README

on:
  schedule:
    - cron: '0 * * * *'  # A cada hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar jq
        run: sudo apt-get install jq

      - name: Rodar script de atualização
        run: bash atualizar_readme.sh

      - name: Ver resultado
        run: cat README.md
