name: Atualizar README com projeto atual

on:
  schedule:
    - cron: "0 * * * *" # A cada 1 hora
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar dependências
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Tornar o script executável
        run: chmod +x atualizar_readme.sh

      - name: Executar script de atualização
        run: ./atualizar_readme.sh
